direction: down

Garmin Connect : {
    shape: image
    icon: ./garmin_icon.png
}

data_fetching: {
    Fetch

    Save to S3

    Fetch -> Save to S3
}

coach: {
    Past data

    OpenAI
    
    Suggestion

    Past data -> OpenAI -> Suggestion
}

online portal: {
    ui: {shape: hexagon}
}


Runner: {
    shape: person
    width: 100
}


Runner -> Garmin Connect: store data
Runner -> online portal: access

Garmin Connect -> data_fetching
data_fetching -> coach: read data
coach -> online portal: publish suggestion