version: '3.8'

services:
  lambda-fetch-suggest:
    build:
      context: .
      dockerfile: lambda.Dockerfile
    environment:
      - DOCKER_BUILDKIT=0
      - GARMIN_USERNAME=${GARMIN_USERNAME}
      - GARMIN_PASSWORD=${GARMIN_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    env_file:
        - .env
    ports:
      - "9001:8080"

  web_app:
    build:
      context: .
      dockerfile: web_app.Dockerfile
    environment:
      - GARMIN_USERNAME=${GARMIN_USERNAME}
      - GARMIN_PASSWORD=${GARMIN_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    ports:
      - 8080:80
