services:
  inference:
    build:
      context: .
      dockerfile: flask_app.Dockerfile
    image: run-tracker
    volumes:
      - ./src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GARMIN_USERNAME=${GARMIN_USERNAME}
      - GARMIN_PASSWORD=${GARMIN_PASSWORD}
      - DUMMY_RESPONSE=${DUMMY_RESPONSE}
    ports:
      - 5000:5000
