direction: right

Garmin Connect : {
    shape: image
    icon: ./garmin_icon.png
}

data_fetching: {
    Fetch

    Save to S3

    Fetch -> Save to S3
}

coach: {
    Past data

    OpenAI

    Suggestion

    Past data -> OpenAI -> Suggestion
}

online portal: {
    UI : {
        shape: hexagon
    }
}

Runner: {
    shape: person
    width: 100
}


Runner -> Garmin Connect: upload
Runner -> online portal: access

Garmin Connect -> data_fetching
data_fetching -> coach: read
coach -> online portal: publish
